app = 'pocketlitellm'
primary_region = 'sin'

cmd = [
  "--host", "0.0.0.0",
  "--config", "/app/deploy/fly/proxy_config.yaml",
  "--port", "4000",
  "--use_prisma_db_push"
]

[env]
  PORT = "4000"
  HOST = "0.0.0.0"
  LITELLM_MODE = "PRODUCTION"
  PYTHONUNBUFFERED = "1"
  OR_SITE_URL = "https://pocketlitellm.fly.dev"
  OR_APP_NAME = "PocketData LiteLLM"

[http_service]
  internal_port = 4000
  force_https = false
  auto_stop_machines = "suspend"
  auto_start_machines = true
  min_machines_running = 0
  [http_service.concurrency]
    type = "requests"
    soft_limit = 250

  [[http_service.checks]]
    interval = "15s"
    grace_period = "30s"
    method = "GET"
    path = "/health/readiness"
    protocol = "http"
    timeout = "5s"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 2
